
DROP TABLE IF EXISTS  ACcharacts;
DROP TABLE IF EXISTS  DCcharacts;
DROP TABLE IF EXISTS  Gcharacts;
DROP TABLE IF EXISTS  Trts;
DROP TABLE IF EXISTS  Devices;
DROP TABLE IF EXISTS  TrtTypes;
DROP TABLE IF EXISTS  Wafers;
DROP TABLE IF EXISTS  Users;
